name: Pre Publish CI

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        uses: actions/checkout@v4
        run: npm run lint
      - name: Tests
        uses: actions/checkout@v4
        run: npm run test
